# languages.py

LANGUAGES = {
    "en": {
        "login_title": "# 🔐 Login",
        "danh_s_ch_ghi_ch_table_view": "### 📊 Danh sách Ghi chú (Table View)",
        "i_m_tin_c_ng_vi_c_kh_n_c_p": "### 🔔 Điểm tin công việc khẩn cấp",
        "b_l_c_t_m_ki_m": "### 🛠️ Bộ lọc & Tìm kiếm",
        "import_actions": "### 🛠️ Import Actions",
        "thao_t_c_x_l": "**⚡ Thao tác xử lý**",
        "n_i_dung_ghi_ch": "**📝 Nội dung ghi chú:**",
        "div_style_margin_top_8px_div": "<div style='margin-top: 8px;'></div>",
        "achievement": "Achievement %",
        "action": "Action",
        "actual_settled_date_target": "Actual Settled Date Target",
        "ad_hoc_tracking_remarks": "Ad-hoc Tracking Remarks",
        "add_revenue": "Add Revenue",
        "admin_only_page": "Admin only page",
        "all_error_logs_deleted": "All error logs deleted",
        "all_logs_deleted": "All logs deleted",
        "amount": "Amount",
        "amount_must_0": "Amount must > 0",
        "asset_operational_history_note": "Asset Operational History Notes & Remarks",
        "assistant": "Assistant",
        "calculated_net_commission_yiel": "Calculated Net Commission Yield",
        "calibration_due_soon": "Calibration Due Soon",
        "calibration_overdue": "Calibration Overdue",
        "calibration_revenue": "Calibration Revenue",
        "cannot_delete_admin": "Cannot delete admin",
        "cert_status_date": "Cert Status Date",
        "certificate_workflow_status": "Certificate Workflow Status",
        "ch_a_nh_p_m_t_kh_u_m_i": "Chưa nhập mật khẩu mới",
        "client_ultimate_confirmed_inta": "Client Ultimate Confirmed Intake Date",
        "client_unit_outbound_dispatch": "Client Unit Outbound Dispatch Date",
        "commission_ratio": "Commission Ratio (%)",
        "commission_revenue": "Commission Revenue",
        "confirm_assistant_transfer": "Confirm Assistant Transfer",
        "confirm_new_password": "Confirm New Password",
        "confirm_sale_transfer": "Confirm Sale Transfer",
        "confirm_move_this_exact_entry": "Confirm move this exact entry to trash storage",
        "consignee_client_asset_in_tran": "Consignee Client Asset In Transit (Not Received Yet)",
        "consignee_received_date_stamp": "Consignee Received Date Stamp",
        "create_user": "Create User",
        "current": "Current",
        "customer": "Customer",
        "customer_name": "Customer Name (*)",
        "c_c_c_ng_vi_c_c_n_ch_trong_3_n": "Các công việc cần chú ý trong 3 ngày tới:",
        "c_c_c_ng_vi_c_sau_v_t_qu_th_i": "Các công việc sau đã VƯỢT QUÁ thời hạn! Vui lòng xử lý ngay:",
        "database_file_not_found": "Database file not found.",
        "database_ready_for_download": "Database ready for download.",
        "delete_user": "Delete User",
        "delete_all_logs_cannot_be_undo": "Delete all logs cannot be undone.",
        "disable_calibration_notificati": "Disable Calibration Notification",
        "disable_document_notification": "Disable Document Notification",
        "disable_payment_notification": "Disable Payment Notification",
        "dispatched_sent_date": "Dispatched Sent Date",
        "document_type_class_name": "Document Type / Class Name (*)",
        "download_current_sqlite_databa": "Download current SQLite database.",
        "enter_new_password": "Enter New Password",
        "entry_safely_extracted_and_dro": "Entry safely extracted and dropped from database branch.",
        "existing_users": "Existing Users",
        "expense_deleted": "Expense deleted",
        "external_customer_name": "External Customer Name (*)",
        "external_dispatch_sent_date": "External Dispatch Sent Date",
        "external_item_pending_not_rece": "External Item Pending (Not Received)",
        "external_item_received_date_st": "External Item Received Date Stamp",
        "filter_customer": "Filter Customer",
        "filter_master_corporate_custom": "Filter Master Corporate Customer",
        "finance": "Finance",
        "from_assistant": "From Assistant",
        "from_sale": "From Sale",
        "gst_final_delivery_release_out": "GST Final Delivery Release Outbound",
        "gst_handover_to_subcontractor": "GST Handover To Subcontractor Date",
        "gst_intake_back_from_subcontra": "GST Intake Back From Subcontractor",
        "gst_operations_intake_receipt": "GST Operations Intake Receipt Date",
        "ghi_ch_n_y_kh_ng_c_n_i_dung_v": "Ghi chú này không có nội dung văn bản.",
        "go_to_page": "Go to page",
        "go_to_page_ad_hoc": "Go to page (Ad-hoc)",
        "go_to_page_master": "Go to page (Master)",
        "hello": "Hello",
        "h_n_ch_t_l_h_m_nay_u_ti_n_ho_n": "Hạn chót là HÔM NAY! Ưu tiên hoàn thành các việc này:",
        "h_n_ho_n_th_nh": "Hạn hoàn thành",
        "h_th_ng_qu_n_l_theo_d_i_ti_n_v": "Hệ thống quản lý, theo dõi tiến độ và đếm ngược thời hạn ghi chú thông minh",
        "i_confirm_importing_historical": "I confirm importing historical data",
        "i_confirm_restore_selected_ord": "I confirm restore selected orders",
        "i_understand_and_want_to_delet": "I understand and want to delete all logs",
        "i_understand_this_action_canno": "I understand this action cannot be undone",
        "i_verify_moving_the_chosen_log": "I verify moving the chosen logs to system trash bin",
        "invoice_distribution_date": "Invoice Distribution Date",
        "invoice_group_code": "Invoice Group Code (*)",
        "kpi_month": "KPI Month",
        "kpi_saved": "KPI Saved",
        "kpi_year": "KPI Year",
        "kh_ng_c_ghi_ch_n_o_th_a_m_n_i": "Không có ghi chú nào thỏa mãn điều kiện lọc.",
        "kh_ng_t_m_th_y_id_ng_i_d_ng_vu": "Không tìm thấy ID người dùng. Vui lòng đăng nhập lại.",
        "kh_ng_t_m_th_y_ghi_ch_n_o_ph_h": "Không tìm thấy ghi chú nào phù hợp.",
        "login": "Login",
        "logistics_remarks_notes": "Logistics Remarks & Notes",
        "logs": "Logs",
        "lo_i": "Loại",
        "lo_i_ghi_ch": "Loại ghi chú",
        "l_p": "Lớp",
        "l_p_theo_d_i": "Lớp theo dõi",
        "manager_only_page": "Manager only page",
        "mapping_saved": "Mapping saved.",
        "mark_as_unpaid_outstanding_deb": "Mark as Unpaid / Outstanding Debt",
        "measurement_date": "Measurement Date",
        "missing_certificate": "Missing Certificate",
        "missing_document_sending": "Missing Document Sending",
        "missing_invoice": "Missing Invoice",
        "month": "Month",
        "monthly_paid_revenue": "Monthly Paid Revenue",
        "m_c_u_ti_n": "Mức độ ưu tiên",
        "next": "Next ➡",
        "no_cert_yet": "No Cert Yet",
        "no_data_found": "No data found",
        "no_due_soon_matching_parameter": "No due soon matching parameters",
        "no_errors_found": "No errors found",
        "no_external_miscellaneous_ad_h": "No external miscellaneous ad-hoc history logs located.",
        "no_localized_operational_track": "No localized operational tracking history available for this item.",
        "no_missing_certificate_matchin": "No missing certificate matching parameters",
        "no_missing_document_sending_ma": "No missing document sending matching parameters",
        "no_missing_invoice_matching_pa": "No missing invoice matching parameters",
        "no_orders_currently_active_and": "No orders currently active and available for clear operations.",
        "no_other_revenue_found": "No other revenue found",
        "no_overdue_calibration_matchin": "No overdue calibration matching parameters",
        "no_overdue_payment_matching_pa": "No overdue payment matching parameters",
        "no_pending_return_matching_par": "No pending return matching parameters",
        "no_permission": "No permission",
        "no_revenue_data_found": "No revenue data found",
        "no_users_available_to_update_p": "No users available to update password.",
        "note": "Note",
        "n_i_dung": "Nội dung",
        "n_i_dung_h_tr_nh_d_ng_markdown": "Nội dung (Hỗ trợ định dạng **Markdown**)",
        "operational_ledger_remarks_not": "Operational Ledger Remarks & Notes",
        "operational_service_routing_ar": "Operational Service Routing Architecture",
        "order_number": "Order Number (*)",
        "orders": "Orders",
        "other_revenue": "Other Revenue",
        "other_revenue_date": "Other Revenue Date",
        "overdue": "Overdue",
        "overdue_analysis": "Overdue Analysis",
        "overdue_revenue": "Overdue Revenue",
        "page": "Page",
        "paid_revenue": "Paid Revenue",
        "password": "Password",
        "password_required": "Password required",
        "payment_overdue": "Payment Overdue",
        "payment_status_distribution": "Payment Status Distribution",
        "payment_terms_30_365_days_cred": "Payment Terms (30 - 365 Days Credit) (*)",
        "payments": "Payments",
        "pending_courier_delivery_not_r": "Pending Courier Delivery (Not Received Yet)",
        "pending_return": "Pending Return",
        "pending_revenue": "Pending Revenue",
        "please_check_i_confirm_inside": "Please check 'I confirm...' inside the form first!",
        "please_confirm_first": "Please confirm first",
        "please_login": "Please login",
        "please_select_at_least_one_ord": "Please select at least one order",
        "please_upload_excel_file": "Please upload Excel file.",
        "remaining": "Remaining",
        "revenue_by_customer": "Revenue By Customer",
        "revenue_trend_by_month": "Revenue Trend By Month",
        "revenue_added": "Revenue added",
        "role": "Role",
        "rows_per_page": "Rows per page",
        "rows_per_page_ad_hoc": "Rows per page (Ad-hoc)",
        "rows_per_page_master": "Rows per page (Master)",
        "sale_owner": "Sale Owner",
        "save_tracking_status": "Save Tracking Status",
        "select_assistant": "Select Assistant",
        "select_expense_to_delete": "Select Expense To Delete",
        "select_order_number_pipeline": "Select Order Number Pipeline",
        "select_orders": "Select Orders",
        "select_orders_to_permanently_d": "Select Orders To Permanently Delete",
        "select_orders_to_restore": "Select Orders To Restore",
        "select_orders_for_disposal_que": "Select Orders for Disposal Queue",
        "select_target_lifecycle_record": "Select Target Lifecycle Record to Void",
        "select_target_master_tracking": "Select Target Master Tracking Entry to Void",
        "select_target_order_number_to": "Select Target Order Number to Erase",
        "select_user": "Select User",
        "select_user_to_change_password": "Select User to change password",
        "subcontract_vendor_dispatches": "Subcontract Vendor Dispatches Directly To End Client",
        "subcontract_vendor_organizatio": "Subcontract Vendor Organization Name (*)",
        "subcontractor_facility_ingesti": "Subcontractor Facility Ingestion Date",
        "subcontractor_fulfillment_rele": "Subcontractor Fulfillment Release Date",
        "supported_sales": "Supported Sales",
        "sync_order_data": "Sync Order Data",
        "system_master_tracking_log_dat": "System master tracking log data repository empty.",
        "target": "Target",
        "target_order_pipeline": "Target Order Pipeline (*)",
        "target_order_pipeline_id": "Target Order Pipeline ID (*)",
        "target_revenue": "Target Revenue",
        "target_asset_operational_footp": "Target asset operational footprint successfully scrubbed.",
        "technical_details": "Technical Details",
        "ti_u": "Tiêu đề *",
        "to_assistant": "To Assistant",
        "to_sale": "To Sale",
        "top_10_customers": "Top 10 Customers",
        "total_invoice_valuation_amount": "Total Invoice Valuation Amount (*)",
        "total_logs": "Total Logs",
        "total_operational_orders": "Total Operational Orders",
        "total_revenue": "Total Revenue",
        "tracking": "Tracking",
        "trang_sau": "Trang sau ➡️",
        "transfer_assistant": "Transfer Assistant",
        "transfer_assistant_revenue": "Transfer Assistant Revenue",
        "transfer_sale": "Transfer Sale",
        "transfer_sale_owner": "Transfer Sale Owner",
        "transfer_completed": "Transfer completed",
        "trash_bin_is_empty": "Trash bin is empty",
        "tr_ng_th_i": "Trạng thái",
        "unexpected_error_occurred_erro": "Unexpected error occurred. Error saved to Error Logs.",
        "update_password": "Update Password",
        "upload_excel_file_structure": "Upload Excel File Structure",
        "upload_historical_excel": "Upload Historical Excel",
        "user_already_exists": "User already exists",
        "user_created": "User created",
        "user_deleted": "User deleted",
        "username": "Username",
        "username_required": "Username required",
        "validation_failed": "Validation Failed",
        "validation_passed_data_h_p_l_1": "Validation Passed! Data hợp lệ 100%.",
        "vui_l_ng_nh_p_ti_u": "Vui lòng nhập tiêu đề",
        "vui_l_ng_i_n_y_username_v_pass": "Vui lòng điền đầy đủ Username và Password.",
        "vui_l_ng_ng_nh_p_xem_ghi_ch": "Vui lòng đăng nhập để xem ghi chú",
        "year": "Year",
        "create_note_form": "create_note_form",
        "edit_note_form": "edit_note_form",
        "login_form": "login_form",
        "update_password_form": "update_password_form",
        "n_trang": "Đến trang:",
        "document_packet_flagged_as_cur": "ℹ️ Document packet flagged as currently transit-bound.",
        "system_flags_this_invoice_reco": "ℹ️ System flags this invoice record balance as pending payment.",
        "permanent_delete": "☠ Permanent Delete",
        "permanent_delete_selected": "☠ Permanent Delete Selected",
        "restore_order": "♻ Restore Order",
        "restore_selected": "♻ Restore Selected",
        "b_l_c_n_ng_cao": "⚙️ Bộ lọc nâng cao",
        "ad_hoc_document_capture_fields": "⚠️ Ad-hoc document capture fields marked (*) must be completed to initialize storage sync.",
        "maintenance": "⚠️ Maintenance",
        "no_available_core_order_entrie": "⚠️ No available core order entries detected under current parameters.",
        "no_available_orders_detected_u": "⚠️ No available orders detected under current parameters.",
        "no_matching_valid_certified_or": "⚠️ No matching valid certified order records located.",
        "please_fill_in_all_required_fi": "⚠️ Please fill in all required fields marked with (*) to activate Sync.",
        "please_provide_the_subcontract": "⚠️ Please provide the Subcontract Vendor Organization Name (*) to authorize save execution.",
        "query_mismatch_no_records_matc": "⚠️ Query mismatch: No records matching keywords.",
        "security_alerts_requests": "⚠️ Security Alerts & Requests",
        "pipeline_active_in_progress": "⚪ Pipeline Active (In Progress)",
        "tr_ng_th_i_an_to_n_kh_ng_c_t_i": "✅ Trạng thái an toàn. Không có tài khoản nhân viên nào bị khóa hoặc yêu cầu reset.",
        "t_o_ghi_ch": "✅ Tạo ghi chú",
        "ch_nh_s_a": "✏️ Chỉnh sửa",
        "ch_nh_s_a_ghi_ch": "✏️ Chỉnh sửa ghi chú",
        "h_y": "❌ Hủy",
        "passwords_do_not_match_please": "❌ Passwords do not match! Please check again.",
        "please_enter_a_new_password": "❌ Please enter a new password.",
        "qu_n_m_t_kh_u": "❓ Quên mật khẩu",
        "register_ad_hoc_document_entry": "➕ Register Ad-hoc Document Entry",
        "previous": "⬅ Previous",
        "trang_tr_c": "⬅️ Trang trước",
        "asset_lifecycle_operational_ma": "🎉 Asset lifecycle operational matrices updated.",
        "excel_dataset_processing_compl": "🎉 Excel dataset processing complete!",
        "invoice_details_safely_committ": "🎉 Invoice details safely committed to master branch.",
        "miscellaneous_ad_hoc_tracking": "🎉 Miscellaneous ad-hoc tracking entry recorded.",
        "order_successfully_synced": "🎉 Order successfully synced!",
        "tracking_baseline_successfully": "🎉 Tracking baseline successfully updated!",
        "tuy_t_v_i_b_n_kh_ng_c_c_ng_vi": "🎉 Tuyệt vời! Bạn không có công việc nào bị quá hạn hoặc quá gấp trong 3 ngày tới.",
        "ng_nh_p_th_nh_c_ng": "🎉 Đăng nhập thành công!",
        "kpi_progress": "🎯 KPI Progress",
        "revenue_kpi": "🎯 Revenue KPI",
        "vui_l_ng_i_n_username_c_a_b_n": "👉 Vui lòng điền Username của bạn vào ô đăng nhập phía trên trước rồi bấm nút này nhé.",
        "assistant_performance": "👥 Assistant Performance",
        "user_management": "👥 User Management",
        "cert_status_will_be_kept_empty": "💡 Cert status will be kept empty.",
        "m_o_nh_p_v_o_tr_n_u_d_ng_c_a_b": "💡 Mẹo: Nhấp vào ô tròn đầu dòng của bảng để chọn xem chi tiết, sửa hoặc xóa ghi chú đó.",
        "payment_invoice_ledger_managem": "💰 Payment & Invoice Ledger Management",
        "revenue_management": "💵 Revenue Management",
        "backup_database": "💾 Backup Database",
        "commit_tracking_entry": "💾 Commit Tracking Entry",
        "c_p_nh_t": "💾 Cập nhật",
        "save_invoice_changes": "💾 Save Invoice Changes",
        "save_kpi": "💾 Save KPI",
        "save_mapping": "💾 Save Mapping",
        "missing_cert": "📄 Missing Cert",
        "page_history": "📄 Page (History)",
        "due_soon": "📅 Due Soon",
        "analytics_dashboard": "📈 Analytics Dashboard",
        "database_statistics": "📈 Database Statistics",
        "dashboard_center": "📊 Dashboard Center",
        "full_erp_archive": "📊 Full ERP Archive",
        "global_document_tracking_ledge": "📊 Global Document Tracking Ledger Master",
        "operational_sla_matrix_perform": "📊 Operational SLA Matrix Performance Dashboard",
        "data_viewer": "📋 Data Viewer",
        "filtered_alert_logs_controller": "📋 Filtered Alert Logs Controller",
        "import_preview": "📋 Import Preview",
        "order_document_tracking": "📋 Order Document Tracking",
        "other_revenue_management": "📋 Other Revenue Management",
        "qu_n_l_ghi_ch": "📋 Quản lý Ghi chú",
        "current_order_selected_trackin": "📜 Current Order Selected Tracking History",
        "t_o_ghi_ch_m_i": "📝 Tạo ghi chú mới",
        "download_all_orders": "📥 Download All Orders",
        "download_filtered_orders": "📥 Download Filtered Orders",
        "export_master_excel_sheet": "📥 Export Master Excel Sheet",
        "historical_data_import": "📥 Historical Data Import",
        "equipment_asset_lifecycle_trac": "📦 Equipment & Asset Lifecycle Tracking",
        "miscellaneous_ad_hoc_document": "📦 Miscellaneous Ad-hoc Document Tracking",
        "miscellaneous_document_trackin": "📦 Miscellaneous Document Tracking History Database",
        "document_tracking_logistics_hu": "📨 Document Tracking & Logistics Hub",
        "missing_send": "📨 Missing Send",
        "l_m_m_i": "🔄 Làm mới",
        "ownership_transfer": "🔄 Ownership Transfer",
        "fast_filter_active_order_custo": "🔍 Fast Filter Active Order / Customer Record Pipeline",
        "fast_query_search_client_accou": "🔍 Fast Query Search Client Account / Target Order Sequence",
        "filter_customer_order_invoice": "🔍 Filter Customer / Order / Invoice Group Global Data",
        "search": "🔍 Search",
        "search_master_database_order_c": "🔍 Search Master Database (Order / Customer / Note Keywords)",
        "t_m_ki_m_nhanh": "🔍 Tìm kiếm nhanh",
        "validate_file": "🔍 Validate File",
        "update_user_password": "🔒 Update User Password",
        "notification_center": "🔔 Notification Center",
        "critical_breach_over_sla": "🔴 Critical Breach (Over SLA)",
        "delete_all_error_logs": "🗑 Delete All Error Logs",
        "delete_all_logs": "🗑 Delete All Logs",
        "delete_revenue": "🗑 Delete Revenue",
        "trash_bin": "🗑 Trash Bin",
        "bulk_move_to_trash_actions": "🗑️ Bulk Move To Trash Actions",
        "delete_single_order_entry": "🗑️ Delete Single Order Entry",
        "move_selected_rows_to_trash": "🗑️ Move Selected Rows To Trash",
        "proceed_single_trash_action": "🗑️ Proceed Single Trash Action",
        "purge_selected_tracking_entry": "🗑️ Purge Selected Tracking Entry",
        "void_selected_asset_lifecycle": "🗑️ Void Selected Asset Lifecycle Log",
        "x_a_ghi_ch": "🗑️ Xóa ghi chú",
        "bulk_sync_from_excel": "🚀 Bulk Sync From Excel",
        "import_to_erp": "🚀 Import To ERP",
        "error_logs": "🚨 Error Logs",
        "threshold_alert_warning": "🟡 Threshold Alert (Warning)",
        "h_m_nay_kh_ng_c_vi_c_n_o_n_h_n": "🟢 Hôm nay không có việc nào đến hạn chót.",
        "kh_ng_c_c_ng_vi_c_n_o_qu_h_n": "🟢 Không có công việc nào quá hạn.",
        "kh_ng_c_vi_c_n_o_g_p_trong_v_i": "🟢 Không có việc nào gấp trong vài ngày tới.",
        "sla_compliant_ok": "🟢 SLA Compliant (OK)",
        "assistant_sale_mapping": "🤝 Assistant - Sale Mapping",
    },
    "vi": {
        "login_title": "# 🔐 Đăng Nhập",
        "danh_s_ch_ghi_ch_table_view": "### 📊 Danh sách Ghi chú (Dạng Bảng)",
        "i_m_tin_c_ng_vi_c_kh_n_c_p": "### 🔔 Điểm tin công việc khẩn cấp",
        "b_l_c_t_m_ki_m": "### 🛠️ Bộ lọc & Tìm kiếm",
        "import_actions": "### 🛠️ Thao tác Nhập dữ liệu (Import)",
        "thao_t_c_x_l": "**⚡ Thao tác xử lý**",
        "n_i_dung_ghi_ch": "**📝 Nội dung ghi chú:**",
        "div_style_margin_top_8px_div": "<div style='margin-top: 8px;'></div>",
        "achievement": "Tỷ lệ Đạt mục tiêu (%)",
        "action": "Thao tác",
        "actual_settled_date_target": "Hạn định ngày quyết toán thực tế",
        "ad_hoc_tracking_remarks": "Ghi chú theo dõi sự vụ (Ad-hoc)",
        "add_revenue": "Thêm Doanh thu",
        "admin_only_page": "Trang dành riêng cho Quản trị viên (Admin)",
        "all_error_logs_deleted": "Đã xóa toàn bộ nhật ký lỗi (Error logs)",
        "all_logs_deleted": "Đã xóa toàn bộ nhật ký hệ thống (Logs)",
        "amount": "Số tiền",
        "amount_must_0": "Số tiền nhập vào phải lớn hơn 0",
        "asset_operational_history_note": "Nhật ký & Ghi chú vận hành tài sản",
        "assistant": "Trợ lý",
        "calculated_net_commission_yiel": "Tỷ suất hoa hồng ròng tạm tính",
        "calibration_due_soon": "Sắp đến hạn Hiệu chuẩn",
        "calibration_overdue": "Quá hạn Hiệu chuẩn",
        "calibration_revenue": "Doanh thu Hiệu chuẩn",
        "cannot_delete_admin": "Không thể xóa tài khoản Admin hệ thống",
        "cert_status_date": "Ngày cập nhật trạng thái Chứng chỉ",
        "certificate_workflow_status": "Trạng thái quy trình Chứng chỉ",
        "ch_a_nh_p_m_t_kh_u_m_i": "Chưa nhập mật khẩu mới",
        "client_ultimate_confirmed_inta": "Ngày khách hàng xác nhận tiếp nhận cuối cùng",
        "client_unit_outbound_dispatch": "Ngày điều động xuất xưởng đơn vị khách hàng",
        "commission_ratio": "Tỷ lệ chiết khấu hoa hồng (%)",
        "commission_revenue": "Doanh thu Hoa hồng",
        "confirm_assistant_transfer": "Xác nhận chuyển giao quyền Trợ lý",
        "confirm_new_password": "Xác nhận mật khẩu mới",
        "confirm_sale_transfer": "Xác nhận bàn giao quyền Sale Owner",
        "confirm_move_this_exact_entry": "Xác nhận chuyển bản ghi chính xác này vào thùng rác hệ thống",
        "consignee_client_asset_in_tran": "Tài sản khách hàng đang vận chuyển (Chưa tiếp nhận)",
        "consignee_received_date_stamp": "Dấu mốc ngày người nhận đã ký nhận",
        "create_user": "Tạo người dùng mới",
        "current": "Hiện tại",
        "customer": "Khách hàng",
        "customer_name": "Tên Khách hàng (*)",
        "c_c_c_ng_vi_c_c_n_ch_trong_3_n": "Các công việc cần chú ý trong 3 ngày tới:",
        "c_c_c_ng_vi_c_sau_v_t_qu_th_i": "Các công việc sau đã VƯỢT QUÁ thời hạn! Vui lòng xử lý ngay:",
        "database_file_not_found": "Không tìm thấy tệp cơ sở dữ liệu (Database file).",
        "database_ready_for_download": "Cơ sở dữ liệu đã sẵn sàng để tải xuống.",
        "delete_user": "Xóa người dùng",
        "delete_all_logs_cannot_be_undo": "Hành động xóa toàn bộ nhật ký sẽ không thể hoàn tác.",
        "disable_calibration_notificati": "Tắt thông báo Hiệu chuẩn",
        "disable_document_notification": "Tắt thông báo Chứng từ",
        "disable_payment_notification": "Tắt thông báo Thanh toán",
        "dispatched_sent_date": "Ngày gửi đơn hàng đi (Dispatched)",
        "document_type_class_name": "Loại chứng từ / Tên phân lớp (*)",
        "download_current_sqlite_databa": "Tải xuống cơ sở dữ liệu SQLite hiện tại.",
        "enter_new_password": "Nhập mật khẩu mới",
        "entry_safely_extracted_and_dro": "Bản ghi đã được trích xuất an toàn và loại bỏ khỏi nhánh dữ liệu.",
        "existing_users": "Danh sách người dùng hiện có",
        "expense_deleted": "Đã xóa khoản chi phí thành công",
        "external_customer_name": "Tên khách hàng ngoài danh mục (*)",
        "external_dispatch_sent_date": "Ngày gửi điều động ra bên ngoài",
        "external_item_pending_not_rece": "Hạng mục ngoài danh mục đang chờ (Chưa tiếp nhận)",
        "external_item_received_date_st": "Dấu mốc ngày tiếp nhận hạng mục ngoài danh mục",
        "filter_customer": "Lọc theo Khách hàng",
        "filter_master_corporate_custom": "Lọc theo Khách hàng Doanh nghiệp Tổng (Master)",
        "finance": "Tài chính",
        "from_assistant": "Từ Trợ lý",
        "from_sale": "Từ Sale Owner",
        "gst_final_delivery_release_out": "Ngày xuất xưởng bàn giao sản phẩm cuối cùng (GST Outbound)",
        "gst_handover_to_subcontractor": "Ngày bàn giao cho Nhà thầu phụ (GST Handover)",
        "gst_intake_back_from_subcontra": "Ngày nhận lại sản phẩm từ Nhà thầu phụ (GST Ingestion)",
        "gst_operations_intake_receipt": "Ngày ký nhận bàn giao nghiệp vụ nội bộ (GST Intake)",
        "ghi_ch_n_y_kh_ng_c_n_i_dung_v": "Ghi chú này không có nội dung văn bản.",
        "go_to_page": "Đi đến trang",
        "go_to_page_ad_hoc": "Đi đến trang sự vụ (Ad-hoc)",
        "go_to_page_master": "Đi đến trang dữ liệu tổng (Master)",
        "hello": "Xin chào",
        "h_n_ch_t_l_h_m_nay_u_ti_n_ho_n": "Hạn chót là HÔM NAY! Ưu tiên hoàn thành các việc này:",
        "h_n_ho_n_th_nh": "Hạn hoàn thành",
        "h_th_ng_qu_n_l_theo_d_i_ti_n_v": "Hệ thống quản lý, theo dõi tiến độ và đếm ngược thời hạn ghi chú thông minh",
        "i_confirm_importing_historical": "Tôi xác nhận muốn nhập dữ liệu lịch sử",
        "i_confirm_restore_selected_ord": "Tôi xác nhận muốn khôi phục các đơn hàng đã chọn",
        "i_understand_and_want_to_delet": "Tôi đã hiểu và vẫn muốn xóa toàn bộ nhật ký hệ thống",
        "i_understand_this_action_canno": "Tôi hiểu hành động này không thể hoàn tác",
        "i_verify_moving_the_chosen_log": "Tôi xác thực việc chuyển các nhật ký được chọn vào thùng rác hệ thống",
        "invoice_distribution_date": "Ngày phát hành/phân phối Hóa đơn",
        "invoice_group_code": "Mã nhóm Hóa đơn (*)",
        "kpi_month": "Tháng tính KPI",
        "kpi_saved": "Đã lưu thông tin KPI",
        "kpi_year": "Năm tính KPI",
        "kh_ng_c_ghi_ch_n_o_th_a_m_n_i": "Không có ghi chú nào thỏa mãn điều kiện lọc.",
        "kh_ng_t_m_th_y_id_ng_i_d_ng_vu": "Không tìm thấy ID người dùng. Vui lòng đăng nhập lại.",
        "kh_ng_t_m_th_y_ghi_ch_n_o_ph_h": "Không tìm thấy ghi chú nào phù hợp.",
        "login": "Đăng nhập",
        "logistics_remarks_notes": "Nhật ký & Ghi chú Logistics",
        "logs": "Nhật ký hệ thống",
        "lo_i": "Loại",
        "lo_i_ghi_ch": "Loại ghi chú",
        "l_p": "Phân lớp",
        "l_p_theo_d_i": "Phân lớp theo dõi",
        "manager_only_page": "Trang dành riêng cho Quản lý (Manager)",
        "mapping_saved": "Đã lưu thiết lập ánh xạ thành công.",
        "mark_as_unpaid_outstanding_deb": "Đánh dấu là Chưa thanh toán / Công nợ tồn đọng",
        "measurement_date": "Ngày đo lường / Kiểm định",
        "missing_certificate": "Thiếu Chứng chỉ",
        "missing_document_sending": "Thiếu Chứng từ gửi đi",
        "missing_invoice": "Thiếu Hóa đơn",
        "month": "Tháng",
        "monthly_paid_revenue": "Doanh thu thực thu theo tháng",
        "m_c_u_ti_n": "Mức độ ưu tiên",
        "next": "Tiếp theo ➡",
        "no_cert_yet": "Chưa có chứng chỉ",
        "no_data_found": "Không tìm thấy dữ liệu phù hợp",
        "no_due_soon_matching_parameter": "Không có hạng mục nào sắp đến hạn theo điều kiện lọc",
        "no_errors_found": "Không phát hiện lỗi nào hệ thống",
        "no_external_miscellaneous_ad_h": "Không tìm thấy nhật ký lịch sử sự vụ ngoài danh mục.",
        "no_localized_operational_track": "Hạng mục này hiện chưa có lịch sử theo dõi vận hành nội bộ.",
        "no_missing_certificate_matchin": "Không có hạng mục thiếu chứng chỉ nào theo điều kiện lọc",
        "no_missing_document_sending_ma": "Không có hạng mục thiếu chứng từ gửi đi nào theo điều kiện lọc",
        "no_missing_invoice_matching_pa": "Không có hạng mục thiếu hóa đơn nào theo điều kiện lọc",
        "no_orders_currently_active_and": "Hiện tại không có đơn hàng nào kích hoạt khả dụng để dọn dẹp.",
        "no_other_revenue_found": "Không tìm thấy nguồn doanh thu khác",
        "no_overdue_calibration_matchin": "Không có hạng mục quá hạn hiệu chuẩn nào theo điều kiện lọc",
        "no_overdue_payment_matching_pa": "Không có khoản thanh toán quá hạn nào theo điều kiện lọc",
        "no_pending_return_matching_par": "Không có đơn hàng chờ trả về nào theo điều kiện lọc",
        "no_permission": "Bạn không có quyền truy cập chức năng này",
        "no_revenue_data_found": "Không tìm thấy dữ liệu doanh thu",
        "no_users_available_to_update_p": "Không có người dùng khả dụng để cập nhật mật khẩu.",
        "note": "Ghi chú",
        "n_i_dung": "Nội dung",
        "n_i_dung_h_tr_nh_d_ng_markdown": "Nội dung (Hỗ trợ định dạng văn bản **Markdown**)",
        "operational_ledger_remarks_not": "Nhật ký sổ cái & Ghi chú vận hành",
        "operational_service_routing_ar": "Kiến trúc luồng điều động dịch vụ vận hành",
        "order_number": "Mã số Đơn hàng (*)",
        "orders": "Đơn hàng",
        "other_revenue": "Doanh thu Khác",
        "other_revenue_date": "Ngày phát sinh Doanh thu khác",
        "overdue": "Quá hạn",
        "overdue_analysis": "Phân tích tình hình Quá hạn",
        "overdue_revenue": "Doanh thu quá hạn công nợ",
        "page": "Trang",
        "paid_revenue": "Doanh thu Thực thu",
        "password": "Mật khẩu",
        "password_required": "Yêu cầu nhập mật khẩu",
        "payment_overdue": "Thanh toán quá hạn",
        "payment_status_distribution": "Cơ cấu trạng thái thanh toán",
        "payment_terms_30_365_days_cred": "Thời hạn thanh toán hạn mức trả chậm (30 - 365 ngày) (*)",
        "payments": "Thanh toán",
        "pending_courier_delivery_not_r": "Đang chuyển phát nhanh (Người nhận chưa ký nhận)",
        "pending_return": "Chờ trả về",
        "pending_revenue": "Doanh thu treo/chờ xử lý",
        "please_check_i_confirm_inside": "Vui lòng tích chọn mục 'Tôi xác nhận...' trong biểu mẫu trước!",
        "please_confirm_first": "Vui lòng xác nhận yêu cầu trước khi thực hiện",
        "please_login": "Vui lòng đăng nhập hệ thống",
        "please_select_at_least_one_ord": "Vui lòng chọn ít nhất một đơn hàng để xử lý",
        "please_upload_excel_file": "Vui lòng tải lên tệp định dạng Excel.",
        "remaining": "Thời gian còn lại",
        "revenue_by_customer": "Doanh thu theo Khách hàng",
        "revenue_trend_by_month": "Xu hướng doanh thu theo tháng",
        "revenue_added": "Đã thêm doanh thu thành công",
        "role": "Vai trò quyền hạn",
        "rows_per_page": "Số dòng hiển thị mỗi trang",
        "rows_per_page_ad_hoc": "Số dòng trên trang sự vụ (Ad-hoc)",
        "rows_per_page_master": "Số dòng trên trang tổng (Master)",
        "sale_owner": "Sale Owner (Phụ trách)",
        "save_tracking_status": "Lưu trạng thái theo dõi",
        "select_assistant": "Chọn Trợ lý",
        "select_expense_to_delete": "Chọn Khoản chi phí cần xóa",
        "select_order_number_pipeline": "Chọn Tuyến mã đơn hàng hệ thống",
        "select_orders": "Chọn các Đơn hàng",
        "select_orders_to_permanently_d": "Chọn các đơn hàng cần Xóa vĩnh viễn",
        "select_orders_to_restore": "Chọn các đơn hàng cần Khôi phục",
        "select_orders_for_disposal_que": "Chọn các đơn hàng đưa vào hàng đợi Hủy bỏ",
        "select_target_lifecycle_record": "Chọn Bản ghi vòng đời mục tiêu để Vô hiệu hóa",
        "select_target_master_tracking": "Chọn Bản ghi theo dõi tổng mục tiêu để Vô hiệu hóa",
        "select_target_order_number_to": "Chọn Mã đơn hàng mục tiêu cần Tẩy xóa dữ liệu",
        "select_user": "Chọn người dùng",
        "select_user_to_change_password": "Chọn người dùng cần đổi mật khẩu",
        "subcontract_vendor_dispatches": "Nhà thầu phụ giao hàng trực tiếp tới Khách hàng cuối",
        "subcontract_vendor_organizatio": "Tên Đơn vị/Nhà thầu phụ ký ước (*)",
        "subcontractor_facility_ingesti": "Ngày nhà thầu phụ tiếp nhận thiết bị vào cơ sở",
        "subcontractor_fulfillment_rele": "Ngày nhà thầu phụ hoàn thành và bàn giao xuất xưởng",
        "supported_sales": "Danh sách Sale được hỗ trợ",
        "sync_order_data": "Đồng bộ dữ liệu Đơn hàng",
        "system_master_tracking_log_dat": "Kho dữ liệu nhật ký theo dõi tổng của hệ thống hiện đang trống.",
        "target": "Mục tiêu",
        "target_order_pipeline": "Tuyến đơn hàng mục tiêu (*)",
        "target_order_pipeline_id": "ID tuyến đơn hàng mục tiêu (*)",
        "target_revenue": "Chỉ tiêu Doanh thu",
        "target_asset_operational_footp": "Đã tẩy sạch dấu vết lịch sử vận hành của tài sản mục tiêu.",
        "technical_details": "Thông số / Chi tiết Kỹ thuật",
        "ti_u": "Tiêu đề *",
        "to_assistant": "Đến Trợ lý",
        "to_sale": "Đến Sale Owner",
        "top_10_customers": "Top 10 Khách hàng lớn nhất",
        "total_invoice_valuation_amount": "Tổng giá trị định giá hóa đơn (*)",
        "total_logs": "Tổng số dòng nhật ký",
        "total_operational_orders": "Tổng số đơn hàng vận hành",
        "total_revenue": "Tổng doanh thu",
        "tracking": "Theo dõi tiến độ",
        "trang_sau": "Trang sau ➡️",
        "transfer_assistant": "Chuyển giao việc Trợ lý",
        "transfer_assistant_revenue": "Chuyển giao doanh thu tính cho Trợ lý",
        "transfer_sale": "Bàn giao quyền Sale Owner",
        "transfer_sale_owner": "Bàn giao nhân sự phụ trách (Sale Owner)",
        "transfer_completed": "Quá trình chuyển giao hoàn tất thành công",
        "trash_bin_is_empty": "Thùng rác hiện đang trống",
        "tr_ng_th_i": "Trạng thái",
        "unexpected_error_occurred_erro": "Có lỗi bất ngờ xảy ra. Chi tiết lỗi đã được ghi vào Nhật ký lỗi hệ thống.",
        "update_password": "Cập nhật mật khẩu",
        "upload_excel_file_structure": "Tải lên cấu trúc tệp Excel",
        "upload_historical_excel": "Tải lên tệp Excel dữ liệu lịch sử",
        "user_already_exists": "Tên người dùng này đã tồn tại trên hệ thống",
        "user_created": "Đã tạo tài khoản người dùng thành công",
        "user_deleted": "Đã xóa người dùng khỏi hệ thống",
        "username": "Tên đăng nhập (Username)",
        "username_required": "Yêu cầu nhập tên đăng nhập",
        "validation_failed": "Kiểm định Dữ liệu Thất bại",
        "validation_passed_data_h_p_l_1": "Kiểm định Hoàn tất! Dữ liệu hợp lệ 100%.",
        "vui_l_ng_nh_p_ti_u": "Vui lòng nhập tiêu đề",
        "vui_l_ng_i_n_y_username_v_pass": "Vui lòng điền đầy đủ Username và Password.",
        "vui_l_ng_ng_nh_p_xem_ghi_ch": "Vui lòng đăng nhập để xem nội dung ghi chú",
        "year": "Năm",
        "create_note_form": "Biểu mẫu tạo ghi chú",
        "edit_note_form": "Biểu mẫu sửa ghi chú",
        "login_form": "Form đăng nhập",
        "update_password_form": "Form cập nhật mật khẩu",
        "n_trang": "Đến trang:",
        "document_packet_flagged_as_cur": "ℹ️ Bộ hồ sơ chứng từ được đánh dấu đang trong quá trình vận chuyển.",
        "system_flags_this_invoice_reco": "ℹ️ Hệ thống ghi nhận số dư hóa đơn này đang trong trạng thái chờ thanh toán.",
        "permanent_delete": "☠ Xóa vĩnh viễn",
        "permanent_delete_selected": "☠ Xóa vĩnh viễn các mục đã chọn",
        "restore_order": "♻ Khôi phục Đơn hàng",
        "restore_selected": "♻ Khôi phục các mục đã chọn",
        "b_l_c_n_ng_cao": "⚙️ Bộ lọc nâng cao",
        "ad_hoc_document_capture_fields": "⚠️ Các trường thu thập chứng từ sự vụ đánh dấu (*) bắt buộc phải hoàn thành để khởi tạo đồng bộ.",
        "maintenance": "⚠️ Hệ thống đang bảo trì",
        "no_available_core_order_entrie": "⚠️ Không phát hiện bản ghi đơn hàng cốt lõi nào khả dụng theo điều kiện lọc hiện tại.",
        "no_available_orders_detected_u": "⚠️ Không phát hiện đơn hàng khả dụng nào theo điều kiện lọc hiện tại.",
        "no_matching_valid_certified_or": "⚠️ Không tìm thấy bản ghi đơn hàng đã kiểm định hợp lệ nào phù hợp.",
        "please_fill_in_all_required_fi": "⚠️ Vui lòng điền đầy đủ các trường bắt buộc đánh dấu (*) để kích hoạt Đồng bộ.",
        "please_provide_the_subcontract": "⚠️ Vui lòng cung cấp Tên Đơn vị/Nhà thầu phụ (*) để cấp quyền thực thi lệnh lưu dữ liệu.",
        "query_mismatch_no_records_matc": "⚠️ Từ khóa không trùng khớp: Không tìm thấy bản ghi nào.",
        "security_alerts_requests": "⚠️ Cảnh báo & Yêu cầu Bảo mật",
        "pipeline_active_in_progress": "⚪ Tiến trình Đang hoạt động (In Progress)",
        "calibration_overdue_icon": "⛔ Quá hạn Hiệu chuẩn",
        "tr_ng_th_i_an_to_n_kh_ng_c_t_i": "✅ Trạng thái an toàn. Không có tài khoản nhân viên nào bị khóa hoặc yêu cầu reset.",
        "t_o_ghi_ch": "✅ Tạo ghi chú",
        "ch_nh_s_a": "✏️ Chỉnh sửa",
        "ch_nh_s_a_ghi_ch": "✏️ Chỉnh sửa ghi chú",
        "h_y": "❌ Hủy",
        "passwords_do_not_match_please": "❌ Xác nhận mật khẩu không khớp! Vui lòng kiểm tra lại.",
        "please_enter_a_new_password": "❌ Vui lòng nhập mật khẩu mới.",
        "qu_n_m_t_kh_u": "❓ Quên mật khẩu",
        "register_ad_hoc_document_entry": "➕ Đăng ký Bản ghi Chứng từ sự vụ (Ad-hoc)",
        "previous": "⬅ Trước đó",
        "trang_tr_c": "⬅️ Trang trước",
        "asset_lifecycle_operational_ma": "🎉 Đã cập nhật ma trận vận hành vòng đời tài sản.",
        "excel_dataset_processing_compl": "🎉 Đã xử lý hoàn tất tệp dữ liệu Excel!",
        "invoice_details_safely_committ": "🎉 Chi tiết hóa đơn đã được ghi nhận an toàn vào nhánh dữ liệu gốc (Master).",
        "miscellaneous_ad_hoc_tracking": "🎉 Đã ghi nhận bản ghi theo dõi sự vụ hỗn hợp thành công.",
        "order_successfully_synced": "🎉 Đồng bộ đơn hàng thành công!",
        "tracking_baseline_successfully": "🎉 Đã cập nhật đường cơ sở theo dõi (Tracking baseline) thành công!",
        "tuy_t_v_i_b_n_kh_ng_c_c_ng_vi": "🎉 Tuyệt vời! Bạn không có công việc nào bị quá hạn hoặc quá gấp trong 3 ngày tới.",
        "ng_nh_p_th_nh_c_ng": "🎉 Đăng nhập thành công!",
        "kpi_progress": "🎯 Tiến độ thực hiện KPI",
        "revenue_kpi": "🎯 Chỉ tiêu Doanh thu KPI",
        "vui_l_ng_i_n_username_c_a_b_n": "👉 Vui lòng điền Username của bạn vào ô đăng nhập phía trên trước rồi bấm nút này nhé.",
        "assistant_performance": "👥 Hiệu suất làm việc Trợ lý",
        "user_management": "👥 Quản lý Người dùng",
        "cert_status_will_be_kept_empty": "💡 Trạng thái chứng chỉ tạm thời sẽ được để trống.",
        "m_o_nh_p_v_o_tr_n_u_d_ng_c_a_b": "💡 Mẹo: Nhấp vào ô tròn đầu dòng của bảng để chọn xem chi tiết, sửa hoặc xóa ghi chú đó.",
        "payment_invoice_ledger_managem": "💰 Quản lý Sổ cái Hóa đơn & Thanh toán",
        "revenue_management": "💵 Quản lý Doanh thu",
        "backup_database": "💾 Sao lưu Cơ sở dữ liệu",
        "commit_tracking_entry": "💾 Lưu bản ghi theo dõi vào Hệ thống",
        "c_p_nh_t": "💾 Cập nhật",
        "save_invoice_changes": "💾 Lưu thay đổi Hóa đơn",
        "save_kpi": "💾 Lưu thông tin KPI",
        "save_mapping": "💾 Lưu thiết lập Ánh xạ",
        "missing_cert": "📄 Thiếu Chứng chỉ (Cert)",
        "page_history": "📄 Trang Lịch sử (History)",
        "due_soon": "📅 Sắp đến hạn",
        "analytics_dashboard": "📈 Bảng điều khiển Phân tích (Analytics)",
        "database_statistics": "📈 Thống kê Cơ sở dữ liệu",
        "dashboard_center": "📊 Trung tâm Điều hành (Dashboard)",
        "full_erp_archive": "📊 Kho Lưu trữ Toàn diện ERP",
        "global_document_tracking_ledge": "📊 Sổ cái Theo dõi Chứng từ Toàn cầu (Master)",
        "operational_sla_matrix_perform": "📊 Bảng phân tích Hiệu suất Ma trận Cam kết Dịch vụ (SLA)",
        "data_viewer": "📋 Trình xem Dữ liệu",
        "filtered_alert_logs_controller": "📋 Bộ kiểm soát Nhật ký Cảnh báo đã lọc",
        "import_preview": "📋 Xem trước dữ liệu Nhập (Import)",
        "order_document_tracking": "📋 Theo dõi Chứng từ Đơn hàng",
        "other_revenue_management": "📋 Quản lý Doanh thu Khác",
        "qu_n_l_ghi_ch": "📋 Quản lý Ghi chú",
        "current_order_selected_trackin": "📜 Lịch sử theo dõi của Đơn hàng được chọn hiện tại",
        "t_o_ghi_ch_m_i": "📝 Tạo ghi chú mới",
        "download_all_orders": "📥 Tải xuống Toàn bộ Đơn hàng",
        "download_filtered_orders": "📥 Tải xuống Đơn hàng đã lọc",
        "export_master_excel_sheet": "📥 Xuất tệp Excel Tổng thể (Master Sheet)",
        "historical_data_import": "📥 Nhập Dữ liệu Lịch sử (Import)",
        "equipment_asset_lifecycle_trac": "📦 Theo dõi Vòng đời Thiết bị & Tài sản",
        "miscellaneous_ad_hoc_document": "📦 Theo dõi Chứng từ Sự vụ (Ad-hoc)",
        "miscellaneous_document_trackin": "📦 Cơ sở dữ liệu Lịch sử theo dõi chứng từ hỗn hợp",
        "document_tracking_logistics_hu": "📨 Trung tâm Điều phối Hồ sơ & Vận chuyển (Logistics)",
        "missing_send": "📨 Thiếu Hồ sơ gửi đi",
        "l_m_m_i": "🔄 Làm mới dữ liệu",
        "ownership_transfer": "🔄 Chuyển giao Quyền sở hữu",
        "fast_filter_active_order_custo": "🔍 Bộ lọc nhanh Tuyến đơn hàng / Bản ghi Khách hàng đang kích hoạt",
        "fast_query_search_client_accou": "🔍 Truy vấn nhanh Tài khoản khách hàng / Chuỗi đơn hàng mục tiêu",
        "filter_customer_order_invoice": "🔍 Lọc tổng thể dữ liệu Khách hàng / Đơn hàng / Nhóm hóa đơn",
        "search": "🔍 Tìm kiếm",
        "search_master_database_order_c": "🔍 Tìm kiếm trong CSDL tổng (Từ khóa Đơn hàng / Khách hàng / Ghi chú)",
        "t_m_ki_m_nhanh": "🔍 Tìm kiếm nhanh",
        "validate_file": "🔍 Xác thực tệp tin",
        "update_user_password": "🔒 Cập nhật Mật khẩu người dùng",
        "notification_center": "🔔 Trung tâm Thông báo",
        "critical_breach_over_sla": "🔴 Vi phạm nghiêm trọng (Vượt quá SLA)",
        "delete_all_error_logs": "🗑 Xóa toàn bộ Nhật ký lỗi",
        "delete_all_logs": "🗑 Xóa toàn bộ Nhật ký hệ thống",
        "delete_revenue": "🗑 Xóa Doanh thu",
        "trash_bin": "🗑 Thùng rác",
        "bulk_move_to_trash_actions": "🗑️ Hành động chuyển hàng loạt vào Thùng rác",
        "delete_single_order_entry": "🗑️ Xóa bản ghi Đơn hàng đơn lẻ",
        "move_selected_rows_to_trash": "🗑️ Chuyển các dòng đã chọn vào Thùng rác",
        "proceed_single_trash_action": "🗑️ Thực hiện hành động xóa đơn lẻ",
        "purge_selected_tracking_entry": "🗑️ Xóa bỏ hoàn toàn bản ghi theo dõi đã chọn",
        "void_selected_asset_lifecycle": "🗑️ Hủy bỏ hiệu lực bản ghi vòng đời tài sản được chọn",
        "x_a_ghi_ch": "🗑️ Xóa ghi chú",
        "bulk_sync_from_excel": "🚀 Đồng bộ hàng loạt từ tệp Excel",
        "import_to_erp": "🚀 Nhập dữ liệu vào hệ thống ERP",
        "error_logs": "🚨 Nhật ký lỗi (Error logs)",
        "threshold_alert_warning": "🟡 Cảnh báo ngưỡng giới hạn (Warning)",
        "h_m_nay_kh_ng_c_vi_c_n_o_n_h_n": "🟢 Hôm nay không có việc nào đến hạn chót.",
        "kh_ng_c_c_ng_vi_c_n_o_qu_h_n": "🟢 Không có công việc nào quá hạn.",
        "kh_ng_c_vi_c_n_o_g_p_trong_v_i": "🟢 Không có việc nào gấp trong vài ngày tới.",
        "sla_compliant_ok": "🟢 Đạt chuẩn cam kết dịch vụ (SLA OK)",
        "assistant_sale_mapping": "🤝 Thiết lập cấu hình Trợ lý - Sale",
    },
    "zh": {
        "login_title": "# 🔐 用户登录",
        "danh_s_ch_ghi_ch_table_view": "### 📊 备忘录列表 (表格视图)",
        "i_m_tin_c_ng_vi_c_kh_n_c_p": "### 🔔 紧急工作简 báo",
        "b_l_c_t_m_ki_m": "### 🛠️ 筛选与搜索",
        "import_actions": "### 🛠️ 数据导入操作",
        "thao_t_c_x_l": "**⚡ 业务处理操作**",
        "n_i_dung_ghi_ch": "**📝 备忘录内容：**",
        "div_style_margin_top_8px_div": "<div style='margin-top: 8px;'></div>",
        "achievement": "业绩达成率 (%)",
        "action": "操作",
        "actual_settled_date_target": "实际结算目标日期",
        "ad_hoc_tracking_remarks": "特殊事务跟踪备注",
        "add_revenue": "添加收入",
        "admin_only_page": "仅限管理员访问页面",
        "all_error_logs_deleted": "所有错误日志已成功删除",
        "all_logs_deleted": "所有系统日志已成功删除",
        "amount": "金额",
        "amount_must_0": "输入金额必须大于 0",
        "asset_operational_history_note": "资产运行历史记录与备注",
        "assistant": "助理",
        "calculated_net_commission_yiel": "预估净佣金收益率",
        "calibration_due_soon": "计量校准即将到期",
        "calibration_overdue": "计量校准已逾期",
        "calibration_revenue": "校准业务收入",
        "cannot_delete_admin": "无法删除系统超级管理员",
        "cert_status_date": "证书状态更新日期",
        "certificate_workflow_status": "证书审批流状态",
        "ch_a_nh_p_m_t_kh_u_m_i": "尚未输入新密码",
        "client_ultimate_confirmed_inta": "客户最终确认接收日期",
        "client_unit_outbound_dispatch": "客户设备出厂发运日期",
        "commission_ratio": "佣金比例 (%)",
        "commission_revenue": "佣金收入",
        "confirm_assistant_transfer": "确认变更助理权限",
        "confirm_new_password": "确认新密码",
        "confirm_sale_transfer": "确认变更销售负责人",
        "confirm_move_this_exact_entry": "确认将该条选中的记录移至系统回收站",
        "consignee_client_asset_in_tran": "客户资产在途（尚未签收）",
        "consignee_received_date_stamp": "收货人签收日期戳",
        "create_user": "创建新用户",
        "current": "当前状态",
        "customer": "客户",
        "customer_name": "客户名称 (*)",
        "c_c_c_ng_vi_c_c_n_ch_trong_3_n": "未来3天内需注意的工作项目：",
        "c_c_c_ng_vi_c_sau_v_t_qu_th_i": "以下工作已超过最后期限！请立即处理：",
        "database_file_not_found": "未找到数据库文件。",
        "database_ready_for_download": "数据库文件已生成，可供下载。",
        "delete_user": "删除用户",
        "delete_all_logs_cannot_be_undo": "清除全部日志的操作将无法撤销。",
        "disable_calibration_notificati": "关闭校准到期提醒",
        "disable_document_notification": "关闭单据状态提醒",
        "disable_payment_notification": "关闭付款催收提醒",
        "dispatched_sent_date": "货物发运拨出日期",
        "document_type_class_name": "单据类型 / 分类名称 (*)",
        "download_current_sqlite_databa": "下载当前最新的 SQLite 数据库。",
        "enter_new_password": "输入新密码",
        "entry_safely_extracted_and_dro": "数据记录已安全提取并从当前数据库分支中移除。",
        "existing_users": "现有系统用户列表",
        "expense_deleted": "费用开支记录已成功删除",
        "external_customer_name": "外部非名录客户名称 (*)",
        "external_dispatch_sent_date": "外部发运寄出日期",
        "external_item_pending_not_rece": "外部待办项目（未接收）",
        "external_item_received_date_st": "外部项目接收日期戳",
        "filter_customer": "按客户筛选",
        "filter_master_corporate_custom": "按大客户主账号筛选",
        "finance": "财务管理",
        "from_assistant": "原助理",
        "from_sale": "原销售负责人",
        "gst_final_delivery_release_out": "产品最终交付出厂日期 (GST Outbound)",
        "gst_handover_to_subcontractor": "移交分包商日期 (GST Handover)",
        "gst_intake_back_from_subcontra": "从分包商处接回产品日期 (GST Ingestion)",
        "gst_operations_intake_receipt": "内部业务签收接收日期 (GST Intake)",
        "ghi_ch_n_y_kh_ng_c_n_i_dung_v": "此备忘录无文本内容。",
        "go_to_page": "跳转至页面",
        "go_to_page_ad_hoc": "跳转至事务管理页 (Ad-hoc)",
        "go_to_page_master": "跳转至总线数据页 (Master)",
        "hello": "您好",
        "h_n_ch_t_l_h_m_nay_u_ti_n_ho_n": "截止日期是今天！请优先完成以下事项：",
        "h_n_ho_n_th_nh": "完成截止时间",
        "h_th_ng_qu_n_l_theo_d_i_ti_n_v": "智能备忘录管理、进度跟踪与工期倒计时系统",
        "i_confirm_importing_historical": "我确认要执行导入历史数据操作",
        "i_confirm_restore_selected_ord": "我确认要执行还原所选订单操作",
        "i_understand_and_want_to_delet": "我已悉知风险并确认清除所有系统日志",
        "i_understand_this_action_canno": "我明白此操作一旦执行将无法撤销",
        "i_verify_moving_the_chosen_log": "我确认将选中的日志条目移至系统回收站",
        "invoice_distribution_date": "发票开具/分发日期",
        "invoice_group_code": "发票组代码 (*)",
        "kpi_month": "KPI 考核月份",
        "kpi_saved": "KPI 考核指标保存成功",
        "kpi_year": "KPI 考核年份",
        "kh_ng_c_ghi_ch_n_o_th_a_m_n_i": "没有符合当前筛选条件的备忘录。",
        "kh_ng_t_m_th_y_id_ng_i_d_ng_vu": "未找到有效的用户 ID，请重新登录系统。",
        "kh_ng_t_m_th_y_ghi_ch_n_o_ph_h": "未找到相匹配的备忘录。",
        "login": "登录",
        "logistics_remarks_notes": "物流执行情况备注与记录",
        "logs": "系统操作日志",
        "lo_i": "类型",
        "lo_i_ghi_ch": "备忘录类型",
        "l_p": "分级",
        "l_p_theo_d_i": "跟踪级别",
        "manager_only_page": "仅限主管/经理访问权限页",
        "mapping_saved": "映射关联配置保存成功。",
        "mark_as_unpaid_outstanding_deb": "标记为未付款 / 滞留应收账款",
        "measurement_date": "检测/校准计量日期",
        "missing_certificate": "证书缺失待补",
        "missing_document_sending": "单据缺失未寄寄",
        "missing_invoice": "发票缺失待开",
        "month": "月份",
        "monthly_paid_revenue": "月度实际到账收入",
        "m_c_u_ti_n": "优先级",
        "next": "下一页 ➡",
        "no_cert_yet": "暂无证书记录",
        "no_data_found": "未找到相关数据",
        "no_due_soon_matching_parameter": "当前筛选条件下无即将到期项目",
        "no_errors_found": "未发现系统运行错误",
        "no_external_miscellaneous_ad_h": "未找到系统外杂项临时事务的历史日志。",
        "no_localized_operational_track": "该项目目前无本地化运营维护跟踪日志。",
        "no_missing_certificate_matchin": "当前筛选条件下无证书缺失项目",
        "no_missing_document_sending_ma": "当前筛选条件下无单据寄送缺失项目",
        "no_missing_invoice_matching_pa": "当前筛选条件下无发票缺失项目",
        "no_orders_currently_active_and": "当前没有处于激活状态且可供清理的订单。",
        "no_other_revenue_found": "未找到其他收入类别数据",
        "no_overdue_calibration_matchin": "当前筛选条件下无逾期计量校准项目",
        "no_overdue_payment_matching_pa": "当前筛选条件下无逾期未付款项目",
        "no_pending_return_matching_par": "当前筛选条件下无等待退回项目",
        "no_permission": "您无权操作或访问此模块",
        "no_revenue_data_found": "未找到营业收入数据",
        "no_users_available_to_update_p": "没有符合密码更新条件的用户。",
        "note": "备注",
        "n_i_dung": "内容明细",
        "n_i_dung_h_tr_nh_d_ng_markdown": "正文内容 (支持 **Markdown** 富文本格式)",
        "operational_ledger_remarks_not": "操作台账明细与运行备注",
        "operational_service_routing_ar": "运营维护服务调度流水架构",
        "order_number": "订单编号 (*)",
        "orders": "订单管理",
        "other_revenue": "其他营业收入",
        "other_revenue_date": "其他收入产生日期",
        "overdue": "已逾期",
        "overdue_analysis": "账期逾期状况分析",
        "overdue_revenue": "应收逾期账款金额",
        "page": "页码",
        "paid_revenue": "实收营业额",
        "password": "密码",
        "password_required": "请输入登录密码",
        "payment_overdue": "已超付款期限",
        "payment_status_distribution": "回款状态结构占比",
        "payment_terms_30_365_days_cred": "信用账期天数限制 (30 - 365 天) (*)",
        "payments": "收付款管理",
        "pending_courier_delivery_not_r": "快递派送中（收件人尚未签收）",
        "pending_return": "待退回处置",
        "pending_revenue": "在途/待定营业收入",
        "please_check_i_confirm_inside": "请先勾选表单内部的 '我确认...' 复选框！",
        "please_confirm_first": "执行此操作前请先确认指令",
        "please_login": "请登录系统以获取操作权限",
        "please_select_at_least_one_ord": "请至少勾选选择一个订单进行处理",
        "please_upload_excel_file": "请上传标准的 Excel 文件。",
        "remaining": "剩余宽限工期",
        "revenue_by_customer": "按客户维度统计收入",
        "revenue_trend_by_month": "月度营业收入趋势分析",
        "revenue_added": "收入记录添加成功",
        "role": "系统角色与权限组",
        "rows_per_page": "每页显示行数",
        "rows_per_page_ad_hoc": "临时事务页每页行数 (Ad-hoc)",
        "rows_per_page_master": "主数据总线页每页行数 (Master)",
        "sale_owner": "负责销售 (Sale Owner)",
        "save_tracking_status": "保存进度跟踪状态",
        "select_assistant": "选定系统助理",
        "select_expense_to_delete": "选择需要删除的费用报销款项",
        "select_order_number_pipeline": "选定流转系统内的订单总线",
        "select_orders": "勾选选择订单",
        "select_orders_to_permanently_d": "选择需要执行永久删除的订单",
        "select_orders_to_restore": "选择需要执行还原操作的订单",
        "select_orders_for_disposal_que": "选择要移入待作废队列的订单",
        "select_target_lifecycle_record": "选择要执行作废失效的目标资产周期记录",
        "select_target_master_tracking": "选择要执行作废失效的目标总线跟踪记录",
        "select_target_order_number_to": "选择需要物理擦除的目标订单号",
        "select_user": "选择用户",
        "select_user_to_change_password": "选择需要修改密码的用户",
        "subcontract_vendor_dispatches": "分包商直接派送发货至最终终端客户",
        "subcontract_vendor_organizatio": "合同约定分包商/外协组织名称 (*)",
        "subcontractor_facility_ingesti": "分包商工厂收妥接收资产日期",
        "subcontractor_fulfillment_rele": "分包商加工完成释放出厂日期",
        "supported_sales": "支持的销售人员名录",
        "sync_order_data": "同步订单流水数据",
        "system_master_tracking_log_dat": "系统主总线跟踪日志数据仓库当前为空。",
        "target": "考核目标",
        "target_order_pipeline": "目标流转订单总线 (*)",
        "target_order_pipeline_id": "目标流转订单总线 ID (*)",
        "target_revenue": "目标营业收入指标",
        "target_asset_operational_footp": "目标资产的日常运营历史痕迹已成功物理擦除。",
        "technical_details": "技术参数与明细",
        "ti_u": "标题 *",
        "to_assistant": "新接收助理",
        "to_sale": "新接管销售",
        "top_10_customers": "前10大核心客户排名",
        "total_invoice_valuation_amount": "发票资产总估价金额 (*)",
        "total_logs": "日志总行数",
        "total_operational_orders": "运营维护订单总数",
        "total_revenue": "总营业收入",
        "tracking": "进度监控",
        "trang_sau": "下一页 ➡️",
        "transfer_assistant": "移交助理工作职能",
        "transfer_assistant_revenue": "移交助理计算业绩份额",
        "transfer_sale": "变更销售负责人权限",
        "transfer_sale_owner": "变更业务销售负责人 (Sale Owner)",
        "transfer_completed": "业务交接及权限变更操作顺利完成",
        "trash_bin_is_empty": "系统垃圾桶目前为空",
        "tr_ng_th_i": "当前状态",
        "unexpected_error_occurred_erro": "系统出现未知突发异常。详细错误已捕获至系统错误日志中。",
        "update_password": "重置用户密码",
        "upload_excel_file_structure": "上传 Excel 结构文件",
        "upload_historical_excel": "上传包含历史数据的 Excel 报表",
        "user_already_exists": "此账号用户名在系统内已存在",
        "user_created": "用户账号创建成功",
        "user_deleted": "该系统用户已被成功物理注销",
        "username": "登录用户名 (Username)",
        "username_required": "登录用户名不能为空",
        "validation_failed": "数据合规性校验不通过",
        "validation_passed_data_h_p_l_1": "校验通过！数据格式与逻辑合规率100%。",
        "vui_l_ng_nh_p_ti_u": "请输入项目标题",
        "vui_l_ng_i_n_y_username_v_pass": "请完整填写登录用户名与密码。",
        "vui_l_ng_ng_nh_p_xem_ghi_ch": "请先登录账号后再查看备忘录明细",
        "year": "年份",
        "create_note_form": "创建新备忘录表单",
        "edit_note_form": "修改备忘录表单",
        "login_form": "用户登录组件",
        "update_password_form": "更新个人密码组件",
        "n_trang": "跳至页码：",
        "document_packet_flagged_as_cur": "ℹ️ 关联的单据文件包裹已被系统标示为在途流转状态。",
        "system_flags_this_invoice_reco": "ℹ️ 系统记录标示此张发票余额处于等待付款结清状态。",
        "permanent_delete": "☠ 彻底删除",
        "permanent_delete_selected": "☠ 彻底删除选中项目",
        "restore_order": "♻ 还原此订单",
        "restore_selected": "♻ 还原选中的项目",
        "b_l_c_n_ng_cao": "⚙️ 高级多维筛选",
        "ad_hoc_document_capture_fields": "⚠️ 临时事务单据采集打 (*) 号的字段必须填写完毕，方可初始化存储同步。",
        "maintenance": "⚠️ 系统核心模块维护中",
        "no_available_core_order_entrie": "⚠️ 基于当前的筛选参数，系统未能检测到任何有效的核心订单记录。",
        "no_available_orders_detected_u": "⚠️ 基于当前的筛选参数，系统未能检测到任何有效订单。",
        "no_matching_valid_certified_or": "⚠️ 数据库未检索到匹配且通过审定合规的有效订单历史记录。",
        "please_fill_in_all_required_fi": "⚠️ 请完整填写所有带 (*) 号的必填项以激活同步更新逻辑。",
        "please_provide_the_subcontract": "⚠️ 请提供外协分包商名称 (*) 以对保存执行操作授予系统鉴权。",
        "query_mismatch_no_records_matc": "⚠️ 查询不匹配：未能检索到包含此关键字的任何记录。",
        "security_alerts_requests": "⚠️ 安全警报与请求事件处理中心",
        "pipeline_active_in_progress": "⚪ 项目生命周期推进中 (In Progress)",
        "calibration_overdue_icon": "⛔ 计量校准严重超期",
        "tr_ng_th_i_an_to_n_kh_ng_c_t_i": "✅ 系统状态安全。当前没有被锁定或申请重置密码的员工账号。",
        "t_o_ghi_ch": "✅ 保存并新建备忘",
        "ch_nh_s_a": "✏️ 变更编辑",
        "ch_nh_s_a_ghi_ch": "✏️ 编辑此备忘录",
        "h_y": "❌ 放弃取消",
        "passwords_do_not_match_please": "❌ 两次输入的密码不一致！请重新检查。",
        "please_enter_a_new_password": "❌ 请在此处输入您的系统新密码。",
        "qu_n_m_t_kh_u": "❓ 找回/忘记密码",
        "register_ad_hoc_document_entry": "➕ 新增临时事务单据资产登记",
        "previous": "⬅ 返回前序",
        "trang_tr_c": "⬅️ 上一页",
        "asset_lifecycle_operational_ma": "🎉 资产全生命周期运营矩阵状态数据已成功同步并更新。",
        "excel_dataset_processing_compl": "🎉 上传的 Excel 数据包已全部解析处理完毕！",
        "invoice_details_safely_committ": "🎉 发票详细账目明细已安全提报并锁定至主总线 (Master)。",
        "miscellaneous_ad_hoc_tracking": "🎉 杂项临时业务监控跟踪流水写入成功。",
        "order_successfully_synced": "🎉 单据订单流水已顺利跨端同步！",
        "tracking_baseline_successfully": "🎉 全局进度管理监控基准线 (Tracking Baseline) 更新成功！",
        "tuy_t_v_i_b_n_kh_ng_c_c_ng_vi": "🎉 极佳！当前您的名下无任何逾期或3天内高度紧急的临期业务。",
        "ng_nh_p_th_nh_c_ng": "🎉 登录成功！系统正在载入鉴权令牌...",
        "kpi_progress": "🎯 KPI 阶段性指标达成进度",
        "revenue_kpi": "🎯 营业收入核心 KPI 指标",
        "vui_l_ng_i_n_username_c_a_b_n": "👉 请先在上方登录框中输入您的用户名（Username）后，再点击此项操作。",
        "assistant_performance": "👥 助理团队业务绩效看板",
        "user_management": "👥 用户账号及账户安全管理",
        "cert_status_will_be_kept_empty": "💡 证书认证状态数据当前将保持留空。",
        "m_o_nh_p_v_o_tr_n_u_d_ng_c_a_b": "💡 提示：点击表格每行首部的单选圆圈，可以选取进行查看明细、编辑变更或物理删除该条备忘。",
        "payment_invoice_ledger_managem": "💰 收付款流转与开票应收台账管理",
        "revenue_management": "💵 全局营业收入监控与管理",
        "backup_database": "💾 归档备份核心数据库",
        "commit_tracking_entry": "💾 提报跟踪流水进系统库",
        "c_p_nh_t": "💾 更新保存",
        "save_invoice_changes": "💾 保存发票流水变更",
        "save_kpi": "💾 保存 KPI 配置指标",
        "save_mapping": "💾 保存归属映射关系",
        "missing_cert": "📄 缺失资格证书",
        "page_history": "📄 系统历史流水归档页 (History)",
        "due_soon": "📅 即期临近截止业务",
        "analytics_dashboard": "📈 数据高维多要素分析看板 (Analytics)",
        "database_statistics": "📈 核心底层数据库状态统计",
        "dashboard_center": "📊 控制总仓运营中心 (Dashboard)",
        "full_erp_archive": "📊 ERP 数据大盘全量归档中心",
        "global_document_tracking_ledge": "📊 全局单据流转与跟踪主台账 (Master)",
        "operational_sla_matrix_perform": "📊 运行交付效能与服务等级协议 (SLA) 控制台",
        "data_viewer": "📋 数据明细底仓查看器",
        "filtered_alert_logs_controller": "📋 已过滤报警日志中控台",
        "import_preview": "📋 导入数据实时预览区",
        "order_document_tracking": "📋 订单及配套单据可视化跟踪",
        "other_revenue_management": "📋 杂项非核心收入管控中心",
        "qu_n_l_ghi_ch": "📋 个人及公共备忘录管理中心",
        "current_order_selected_trackin": "📜 选定订单当前全链路生命周期流转历史",
        "t_o_ghi_ch_m_i": "📝 撰写新建备忘录",
        "download_all_orders": "📥 全量导出备份所有订单",
        "download_filtered_orders": "📥 导出当前筛选的订单数据",
        "export_master_excel_sheet": "📥 导出主总线全量 Excel 控制报表",
        "historical_data_import": "📥 历史大盘数据一键导入",
        "equipment_asset_lifecycle_trac": "📦 设施设备与固定资产全生命周期监控",
        "miscellaneous_ad_hoc_document": "📦 临时不定期单据处理监控",
        "miscellaneous_document_trackin": "📦 杂项单据资产跟踪维护历史底层数据库",
        "document_tracking_logistics_hu": "📨 单据流转调度与后勤供应链核心仓 (Logistics)",
        "missing_send": "📨 缺失寄出寄递文件",
        "l_m_m_i": "🔄 刷新缓存数据",
        "ownership_transfer": "🔄 业务归属及底账所有人流转",
        "fast_filter_active_order_custo": "🔍 激活态订单 / 客户档案管道快速多维筛选",
        "fast_query_search_client_accou": "🔍 客户账户标识 / 目标订单序列快速精准检索",
        "filter_customer_order_invoice": "🔍 客户 / 订单流水 / 发票分组全局交叉深度筛选",
        "search": "🔍 条件搜索",
        "search_master_database_order_c": "🔍 检索系统全局总仓（包含订单、客户档案、备忘录关键字）",
        "t_m_ki_m_nhanh": "🔍 全局敏捷检索",
        "validate_file": "🔍 校验文件架构合规性",
        "update_user_password": "🔒 修改用户系统访问口令",
        "notification_center": "🔔 系统消息与通知中心",
        "critical_breach_over_sla": "🔴 触发严重红色预警（已严重超出 SLA 约定账期）",
        "delete_all_error_logs": "🗑 清空所有底层错误日志",
        "delete_all_logs": "🗑 清空所有常规系统日志",
        "delete_revenue": "🗑 删除此笔收入记录",
        "trash_bin": "🗑 系统回收站",
        "bulk_move_to_trash_actions": "🗑️ 批量移入回收站安全管控操作",
        "delete_single_order_entry": "🗑️ 物理删除单笔订单信息",
        "move_selected_rows_to_trash": "🗑️ 将勾选的行记录安全移入回收站",
        "proceed_single_trash_action": "🗑️ 触发单条数据作废移除逻辑",
        "purge_selected_tracking_entry": "🗑️ 彻底粉碎清除所选的跟踪信息",
        "void_selected_asset_lifecycle": "🗑️ 作废清除选定的资产周期运行日志",
        "x_a_ghi_ch": "🗑️ 删除此备忘录",
        "bulk_sync_from_excel": "🚀 从 Excel 报表批量执行无缝同步",
        "import_to_erp": "🚀 写入导入至系统 ERP 核心仓",
        "error_logs": "🚨 系统突发错误异常日志 (Error Logs)",
        "threshold_alert_warning": "🟡 临界阈值黄色警告 (Warning)",
        "h_m_nay_kh_ng_c_vi_c_n_o_n_h_n": "🟢 状态良好。今日名下无任何截止到期的业务线。",
        "kh_ng_c_c_ng_vi_c_n_o_qu_h_n": "🟢 状态良好。当前无任何发生流转逾期的工作项目。",
        "kh_ng_c_vi_c_n_o_g_p_trong_v_i": "🟢 状态良好。近期无临近紧急催办的待办项。",
        "sla_compliant_ok": "🟢 符合常态化交付时效控制标准 (SLA OK)",
        "assistant_sale_mapping": "🤝 配置销售人员 - 助理团队归属映射矩阵",
    }
}

# THÊM ĐOẠN NÀY VÀO CUỐI FILE LANGUAGES.PY
import streamlit as st

def t(key):
    """Hàm dịch thuật dùng chung cho toàn bộ hệ thống ERP"""
    chosen_lang = st.session_state.get('language', 'Tiếng Việt')
    lang_map = {
        "Tiếng Việt": "vi",
        "English": "en",
        "🇨🇳 中文 (简体)": "zh"
    }
    lang_code = lang_map.get(chosen_lang, "vi")
    return LANGUAGES.get(lang_code, {}).get(key, key)